// SINGLE SOURCE OF TRUTH — gallery images.
// All entries below are real Futurex event photos sourced from the live futurextrade.com
// gallery and downloaded into /public/images/gallery/. If a file is ever removed, the
// GalleryImage component shows a premium gradient placeholder instead of a broken image,
// so this file stays safe to ship even if an asset goes missing later.

export type GalleryItem = {
  id: string;
  src: string;
  alt: string;
  category: string;
  year: string;
  location: string;
  type:
    | "exhibitions"
    | "conferences"
    | "corporate-events"
    | "webinars"
    | "virtual-platform"
    | "media-coverage";
  /** Short, evocative hover caption used on the homepage gallery preview. */
  moment: string;
};

export const GALLERY_CATEGORIES = [
  "All",
  "Exhibitions",
  "Conferences",
  "Corporate Events",
  "Webinars",
  "Virtual Platform",
  "Media Coverage",
] as const;

export const GALLERY_ITEMS: GalleryItem[] = [
  {
    id: "nepal-wood-2019",
    src: "/images/gallery/nepal-wood-expo-2019.webp",
    alt: "Exhibition hall overview at Nepal Wood International Expo 2019 in Kathmandu",
    category: "Nepal Wood International Expo",
    year: "2019",
    location: "Kathmandu, Nepal",
    type: "exhibitions",
    moment: "Exhibitors showcasing to the trade floor",
  },
  {
    id: "nepal-agritech-2019",
    src: "/images/gallery/nepal-agritech-expo-2019.webp",
    alt: "Exhibitor stalls at Nepal Agritech International Expo 2019",
    category: "Nepal Agritech International Expo",
    year: "2019",
    location: "Kathmandu, Nepal",
    type: "exhibitions",
    moment: "Exhibitors meeting buyers",
  },
  {
    id: "nepal-buildcon-2019",
    src: "/images/gallery/nepal-buildcon-expo-2019.webp",
    alt: "Business visitors at Nepal Buildcon International Expo 2019",
    category: "Nepal Buildcon International Expo",
    year: "2019",
    location: "Kathmandu, Nepal",
    type: "exhibitions",
    moment: "Business visitors exploring the floor",
  },
  {
    id: "bangladesh-buildcon-2019",
    src: "/images/gallery/bangladesh-buildcon-expo-2019.webp",
    alt: "Exhibition floor at Bangladesh Buildcon International Expo 2019 in Dhaka",
    category: "Bangladesh Buildcon International Expo",
    year: "2019",
    location: "Dhaka, Bangladesh",
    type: "exhibitions",
    moment: "Markets connected through Futurex platforms",
  },
  {
    id: "bangladesh-wood-2018",
    src: "/images/gallery/bangladesh-wood-expo-2018.webp",
    alt: "Exhibitor booths at Bangladesh Wood International Expo 2018",
    category: "Bangladesh Wood International Expo",
    year: "2018",
    location: "Dhaka, Bangladesh",
    type: "exhibitions",
    moment: "Exhibitors meeting buyers",
  },
  {
    id: "srilanka-buildcon-2019",
    src: "/images/gallery/srilanka-buildcon-expo-2019.webp",
    alt: "Exhibition hall at Sri Lanka Buildcon International Expo 2019",
    category: "Sri Lanka Buildcon International Expo",
    year: "2019",
    location: "Colombo, Sri Lanka",
    type: "exhibitions",
    moment: "Exhibition hall in full swing",
  },
  {
    id: "bhutan-buildcon-2019",
    src: "/images/gallery/bhutan-buildcon-expo-2019.webp",
    alt: "Exhibition floor at Bhutan Buildcon International Expo 2019 in Thimphu",
    category: "Bhutan Buildcon International Expo",
    year: "2019",
    location: "Thimphu, Bhutan",
    type: "exhibitions",
    moment: "Booth interactions on the exhibition floor",
  },
  {
    id: "futurex-building-specifiers-conference-2018",
    src: "/images/gallery/futurex-industry-conference-1.webp",
    alt: "Stage and screen at the 4th International Building Specifiers Conference 2018, Kathmandu",
    category: "International Building Specifiers Conference",
    year: "2018",
    location: "Kathmandu, Nepal",
    type: "conferences",
    moment: "Industry leaders in conversation",
  },
  {
    id: "futurex-conference-delegates-2018",
    src: "/images/gallery/futurex-industry-conference-2.webp",
    alt: "Industry delegates networking at a Futurex-organized conference",
    category: "Industry Delegate Networking",
    year: "2018",
    location: "Kathmandu, Nepal",
    type: "corporate-events",
    moment: "Delegates networking after the session",
  },
  {
    id: "nepal-5p-expo-1",
    src: "/images/gallery/exhibitions/nepal-5p-expo-1.webp",
    alt: "Nepal 5P International Expo — Kathmandu, Nepal",
    category: "Nepal 5P International Expo",
    year: "2022",
    location: "Kathmandu, Nepal",
    type: "exhibitions",
    moment: "Exhibitors showcasing to the trade floor",
  },
  {
    id: "nepal-5p-expo-2",
    src: "/images/gallery/exhibitions/nepal-5p-expo-2.webp",
    alt: "Nepal 5P International Expo — Kathmandu, Nepal",
    category: "Nepal 5P International Expo",
    year: "2022",
    location: "Kathmandu, Nepal",
    type: "exhibitions",
    moment: "Exhibitors showcasing to the trade floor",
  },
  {
    id: "nepal-5p-expo-3",
    src: "/images/gallery/exhibitions/nepal-5p-expo-3.webp",
    alt: "Nepal 5P International Expo — Kathmandu, Nepal",
    category: "Nepal 5P International Expo",
    year: "2022",
    location: "Kathmandu, Nepal",
    type: "exhibitions",
    moment: "Exhibitors showcasing to the trade floor",
  },
  {
    id: "nepal-agritech-expo-2022-1",
    src: "/images/gallery/exhibitions/nepal-agritech-expo-2022-1.webp",
    alt: "Nepal Agritech International Expo — Kathmandu, Nepal",
    category: "Nepal Agritech International Expo",
    year: "2022",
    location: "Kathmandu, Nepal",
    type: "exhibitions",
    moment: "Exhibitors showcasing to the trade floor",
  },
  {
    id: "nepal-agritech-expo-2022-2",
    src: "/images/gallery/exhibitions/nepal-agritech-expo-2022-2.webp",
    alt: "Nepal Agritech International Expo — Kathmandu, Nepal",
    category: "Nepal Agritech International Expo",
    year: "2022",
    location: "Kathmandu, Nepal",
    type: "exhibitions",
    moment: "Exhibitors showcasing to the trade floor",
  },
  {
    id: "nepal-agritech-expo-2022-3",
    src: "/images/gallery/exhibitions/nepal-agritech-expo-2022-3.webp",
    alt: "Nepal Agritech International Expo — Kathmandu, Nepal",
    category: "Nepal Agritech International Expo",
    year: "2022",
    location: "Kathmandu, Nepal",
    type: "exhibitions",
    moment: "Exhibitors showcasing to the trade floor",
  },
  {
    id: "nepal-buildcon-expo-2022-1",
    src: "/images/gallery/exhibitions/nepal-buildcon-expo-2022-1.webp",
    alt: "Nepal Buildcon International Expo — Kathmandu, Nepal",
    category: "Nepal Buildcon International Expo",
    year: "2022",
    location: "Kathmandu, Nepal",
    type: "exhibitions",
    moment: "Exhibitors showcasing to the trade floor",
  },
  {
    id: "nepal-buildcon-expo-2022-2",
    src: "/images/gallery/exhibitions/nepal-buildcon-expo-2022-2.webp",
    alt: "Nepal Buildcon International Expo — Kathmandu, Nepal",
    category: "Nepal Buildcon International Expo",
    year: "2022",
    location: "Kathmandu, Nepal",
    type: "exhibitions",
    moment: "Exhibitors showcasing to the trade floor",
  },
  {
    id: "nepal-buildcon-expo-2022-3",
    src: "/images/gallery/exhibitions/nepal-buildcon-expo-2022-3.webp",
    alt: "Nepal Buildcon International Expo — Kathmandu, Nepal",
    category: "Nepal Buildcon International Expo",
    year: "2022",
    location: "Kathmandu, Nepal",
    type: "exhibitions",
    moment: "Exhibitors showcasing to the trade floor",
  },
  {
    id: "nepal-food-beverages-expo-1",
    src: "/images/gallery/exhibitions/nepal-food-beverages-expo-1.webp",
    alt: "Nepal Food & Beverages Expo — Kathmandu, Nepal",
    category: "Nepal Food & Beverages Expo",
    year: "2022",
    location: "Kathmandu, Nepal",
    type: "exhibitions",
    moment: "Exhibitors showcasing to the trade floor",
  },
  {
    id: "nepal-food-beverages-expo-2",
    src: "/images/gallery/exhibitions/nepal-food-beverages-expo-2.webp",
    alt: "Nepal Food & Beverages Expo — Kathmandu, Nepal",
    category: "Nepal Food & Beverages Expo",
    year: "2022",
    location: "Kathmandu, Nepal",
    type: "exhibitions",
    moment: "Exhibitors showcasing to the trade floor",
  },
  {
    id: "nepal-food-beverages-expo-3",
    src: "/images/gallery/exhibitions/nepal-food-beverages-expo-3.webp",
    alt: "Nepal Food & Beverages Expo — Kathmandu, Nepal",
    category: "Nepal Food & Beverages Expo",
    year: "2022",
    location: "Kathmandu, Nepal",
    type: "exhibitions",
    moment: "Exhibitors showcasing to the trade floor",
  },
  {
    id: "nepal-wood-expo-2022-1",
    src: "/images/gallery/exhibitions/nepal-wood-expo-2022-1.webp",
    alt: "Nepal Wood International Expo — Kathmandu, Nepal",
    category: "Nepal Wood International Expo",
    year: "2022",
    location: "Kathmandu, Nepal",
    type: "exhibitions",
    moment: "Exhibitors showcasing to the trade floor",
  },
  {
    id: "nepal-wood-expo-2022-2",
    src: "/images/gallery/exhibitions/nepal-wood-expo-2022-2.webp",
    alt: "Nepal Wood International Expo — Kathmandu, Nepal",
    category: "Nepal Wood International Expo",
    year: "2022",
    location: "Kathmandu, Nepal",
    type: "exhibitions",
    moment: "Exhibitors showcasing to the trade floor",
  },
  {
    id: "nepal-wood-expo-2022-3",
    src: "/images/gallery/exhibitions/nepal-wood-expo-2022-3.webp",
    alt: "Nepal Wood International Expo — Kathmandu, Nepal",
    category: "Nepal Wood International Expo",
    year: "2022",
    location: "Kathmandu, Nepal",
    type: "exhibitions",
    moment: "Exhibitors showcasing to the trade floor",
  },
  {
    id: "bangladesh-wood-expo-1",
    src: "/images/gallery/exhibitions/bangladesh-wood-expo-1.webp",
    alt: "Bangladesh Wood International Expo — Dhaka, Bangladesh",
    category: "Bangladesh Wood International Expo",
    year: "2022",
    location: "Dhaka, Bangladesh",
    type: "exhibitions",
    moment: "Exhibitors showcasing to the trade floor",
  },
  {
    id: "bangladesh-wood-expo-2",
    src: "/images/gallery/exhibitions/bangladesh-wood-expo-2.webp",
    alt: "Bangladesh Wood International Expo — Dhaka, Bangladesh",
    category: "Bangladesh Wood International Expo",
    year: "2022",
    location: "Dhaka, Bangladesh",
    type: "exhibitions",
    moment: "Exhibitors showcasing to the trade floor",
  },
  {
    id: "bangladesh-wood-expo-3",
    src: "/images/gallery/exhibitions/bangladesh-wood-expo-3.webp",
    alt: "Bangladesh Wood International Expo — Dhaka, Bangladesh",
    category: "Bangladesh Wood International Expo",
    year: "2022",
    location: "Dhaka, Bangladesh",
    type: "exhibitions",
    moment: "Exhibitors showcasing to the trade floor",
  },
  {
    id: "indo-nepal-expo-1",
    src: "/images/gallery/exhibitions/indo-nepal-expo-1.webp",
    alt: "Indo-Nepal International Expo — Kathmandu, Nepal",
    category: "Indo-Nepal International Expo",
    year: "2022",
    location: "Kathmandu, Nepal",
    type: "exhibitions",
    moment: "Exhibitors showcasing to the trade floor",
  },
  {
    id: "indo-nepal-expo-2",
    src: "/images/gallery/exhibitions/indo-nepal-expo-2.webp",
    alt: "Indo-Nepal International Expo — Kathmandu, Nepal",
    category: "Indo-Nepal International Expo",
    year: "2022",
    location: "Kathmandu, Nepal",
    type: "exhibitions",
    moment: "Exhibitors showcasing to the trade floor",
  },
  {
    id: "indo-nepal-expo-3",
    src: "/images/gallery/exhibitions/indo-nepal-expo-3.webp",
    alt: "Indo-Nepal International Expo — Kathmandu, Nepal",
    category: "Indo-Nepal International Expo",
    year: "2022",
    location: "Kathmandu, Nepal",
    type: "exhibitions",
    moment: "Exhibitors showcasing to the trade floor",
  },
  {
    id: "bangladesh-3p-expo-1",
    src: "/images/gallery/exhibitions/bangladesh-3p-expo-1.webp",
    alt: "Bangladesh 3P Expo — Dhaka, Bangladesh",
    category: "Bangladesh 3P Expo",
    year: "2022",
    location: "Dhaka, Bangladesh",
    type: "exhibitions",
    moment: "Exhibitors showcasing to the trade floor",
  },
  {
    id: "bangladesh-3p-expo-2",
    src: "/images/gallery/exhibitions/bangladesh-3p-expo-2.webp",
    alt: "Bangladesh 3P Expo — Dhaka, Bangladesh",
    category: "Bangladesh 3P Expo",
    year: "2022",
    location: "Dhaka, Bangladesh",
    type: "exhibitions",
    moment: "Exhibitors showcasing to the trade floor",
  },
  {
    id: "bangladesh-3p-expo-3",
    src: "/images/gallery/exhibitions/bangladesh-3p-expo-3.webp",
    alt: "Bangladesh 3P Expo — Dhaka, Bangladesh",
    category: "Bangladesh 3P Expo",
    year: "2022",
    location: "Dhaka, Bangladesh",
    type: "exhibitions",
    moment: "Exhibitors showcasing to the trade floor",
  },
  {
    id: "bhutan-buildcon-wood-expo-1",
    src: "/images/gallery/exhibitions/bhutan-buildcon-wood-expo-1.webp",
    alt: "Bhutan Buildcon & Wood Expo — Thimphu, Bhutan",
    category: "Bhutan Buildcon & Wood Expo",
    year: "2022",
    location: "Thimphu, Bhutan",
    type: "exhibitions",
    moment: "Exhibitors showcasing to the trade floor",
  },
  {
    id: "india-international-ev-show-1",
    src: "/images/gallery/exhibitions/india-international-ev-show-1.webp",
    alt: "India International EV Show — New Delhi, India",
    category: "India International EV Show",
    year: "2022",
    location: "New Delhi, India",
    type: "exhibitions",
    moment: "Exhibitors showcasing to the trade floor",
  },
  {
    id: "india-international-ev-show-2",
    src: "/images/gallery/exhibitions/india-international-ev-show-2.webp",
    alt: "India International EV Show — New Delhi, India",
    category: "India International EV Show",
    year: "2022",
    location: "New Delhi, India",
    type: "exhibitions",
    moment: "Exhibitors showcasing to the trade floor",
  },
  {
    id: "india-international-ev-show-3",
    src: "/images/gallery/exhibitions/india-international-ev-show-3.webp",
    alt: "India International EV Show — New Delhi, India",
    category: "India International EV Show",
    year: "2022",
    location: "New Delhi, India",
    type: "exhibitions",
    moment: "Exhibitors showcasing to the trade floor",
  },
  {
    id: "odisha-buildcon-expo-1",
    src: "/images/gallery/exhibitions/odisha-buildcon-expo-1.webp",
    alt: "Odisha Buildcon International Expo — Bhubaneswar, India",
    category: "Odisha Buildcon International Expo",
    year: "2022",
    location: "Bhubaneswar, India",
    type: "exhibitions",
    moment: "Exhibitors showcasing to the trade floor",
  },
  {
    id: "odisha-buildcon-expo-2",
    src: "/images/gallery/exhibitions/odisha-buildcon-expo-2.webp",
    alt: "Odisha Buildcon International Expo — Bhubaneswar, India",
    category: "Odisha Buildcon International Expo",
    year: "2022",
    location: "Bhubaneswar, India",
    type: "exhibitions",
    moment: "Exhibitors showcasing to the trade floor",
  },
  {
    id: "odisha-buildcon-expo-3",
    src: "/images/gallery/exhibitions/odisha-buildcon-expo-3.webp",
    alt: "Odisha Buildcon International Expo — Bhubaneswar, India",
    category: "Odisha Buildcon International Expo",
    year: "2022",
    location: "Bhubaneswar, India",
    type: "exhibitions",
    moment: "Exhibitors showcasing to the trade floor",
  },
  {
    id: "odisha-wood-expo-1",
    src: "/images/gallery/exhibitions/odisha-wood-expo-1.webp",
    alt: "Odisha Wood International Expo — Bhubaneswar, India",
    category: "Odisha Wood International Expo",
    year: "2022",
    location: "Bhubaneswar, India",
    type: "exhibitions",
    moment: "Exhibitors showcasing to the trade floor",
  },
  {
    id: "odisha-wood-expo-2",
    src: "/images/gallery/exhibitions/odisha-wood-expo-2.webp",
    alt: "Odisha Wood International Expo — Bhubaneswar, India",
    category: "Odisha Wood International Expo",
    year: "2022",
    location: "Bhubaneswar, India",
    type: "exhibitions",
    moment: "Exhibitors showcasing to the trade floor",
  },
  {
    id: "odisha-wood-expo-3",
    src: "/images/gallery/exhibitions/odisha-wood-expo-3.webp",
    alt: "Odisha Wood International Expo — Bhubaneswar, India",
    category: "Odisha Wood International Expo",
    year: "2022",
    location: "Bhubaneswar, India",
    type: "exhibitions",
    moment: "Exhibitors showcasing to the trade floor",
  },
  {
    id: "nepal-power-electric-light-expo-1",
    src: "/images/gallery/exhibitions/nepal-power-electric-light-expo-1.webp",
    alt: "Nepal Power, Electric & Light Expo — Kathmandu, Nepal",
    category: "Nepal Power, Electric & Light Expo",
    year: "2022",
    location: "Kathmandu, Nepal",
    type: "exhibitions",
    moment: "Exhibitors showcasing to the trade floor",
  },
  {
    id: "nepal-power-electric-light-expo-2",
    src: "/images/gallery/exhibitions/nepal-power-electric-light-expo-2.webp",
    alt: "Nepal Power, Electric & Light Expo — Kathmandu, Nepal",
    category: "Nepal Power, Electric & Light Expo",
    year: "2022",
    location: "Kathmandu, Nepal",
    type: "exhibitions",
    moment: "Exhibitors showcasing to the trade floor",
  },
  {
    id: "nepal-power-electric-light-expo-3",
    src: "/images/gallery/exhibitions/nepal-power-electric-light-expo-3.webp",
    alt: "Nepal Power, Electric & Light Expo — Kathmandu, Nepal",
    category: "Nepal Power, Electric & Light Expo",
    year: "2022",
    location: "Kathmandu, Nepal",
    type: "exhibitions",
    moment: "Exhibitors showcasing to the trade floor",
  },
  {
    id: "nepal-pharma-expo-1",
    src: "/images/gallery/exhibitions/nepal-pharma-expo-1.webp",
    alt: "Nepal Pharma International Expo — Kathmandu, Nepal",
    category: "Nepal Pharma International Expo",
    year: "2022",
    location: "Kathmandu, Nepal",
    type: "exhibitions",
    moment: "Exhibitors showcasing to the trade floor",
  },
  {
    id: "nepal-pharma-expo-2",
    src: "/images/gallery/exhibitions/nepal-pharma-expo-2.webp",
    alt: "Nepal Pharma International Expo — Kathmandu, Nepal",
    category: "Nepal Pharma International Expo",
    year: "2022",
    location: "Kathmandu, Nepal",
    type: "exhibitions",
    moment: "Exhibitors showcasing to the trade floor",
  },
  {
    id: "nepal-pharma-expo-3",
    src: "/images/gallery/exhibitions/nepal-pharma-expo-3.webp",
    alt: "Nepal Pharma International Expo — Kathmandu, Nepal",
    category: "Nepal Pharma International Expo",
    year: "2022",
    location: "Kathmandu, Nepal",
    type: "exhibitions",
    moment: "Exhibitors showcasing to the trade floor",
  },
  {
    id: "nepal-wood-international-expo-1",
    src: "/images/gallery/exhibitions/nepal-wood-international-expo-1.webp",
    alt: "Nepal Wood International Expo — Kathmandu, Nepal",
    category: "Nepal Wood International Expo",
    year: "2022",
    location: "Kathmandu, Nepal",
    type: "exhibitions",
    moment: "Exhibitors showcasing to the trade floor",
  },
  {
    id: "nepal-wood-international-expo-2",
    src: "/images/gallery/exhibitions/nepal-wood-international-expo-2.webp",
    alt: "Nepal Wood International Expo — Kathmandu, Nepal",
    category: "Nepal Wood International Expo",
    year: "2022",
    location: "Kathmandu, Nepal",
    type: "exhibitions",
    moment: "Exhibitors showcasing to the trade floor",
  },
  {
    id: "nepal-wood-international-expo-3",
    src: "/images/gallery/exhibitions/nepal-wood-international-expo-3.webp",
    alt: "Nepal Wood International Expo — Kathmandu, Nepal",
    category: "Nepal Wood International Expo",
    year: "2022",
    location: "Kathmandu, Nepal",
    type: "exhibitions",
    moment: "Exhibitors showcasing to the trade floor",
  },
  {
    id: "nepal-agritech-international-expo-1",
    src: "/images/gallery/exhibitions/nepal-agritech-international-expo-1.webp",
    alt: "Nepal Agritech International Expo — Kathmandu, Nepal",
    category: "Nepal Agritech International Expo",
    year: "2022",
    location: "Kathmandu, Nepal",
    type: "exhibitions",
    moment: "Exhibitors showcasing to the trade floor",
  },
  {
    id: "nepal-agritech-international-expo-2",
    src: "/images/gallery/exhibitions/nepal-agritech-international-expo-2.webp",
    alt: "Nepal Agritech International Expo — Kathmandu, Nepal",
    category: "Nepal Agritech International Expo",
    year: "2022",
    location: "Kathmandu, Nepal",
    type: "exhibitions",
    moment: "Exhibitors showcasing to the trade floor",
  },
  {
    id: "nepal-agritech-international-expo-3",
    src: "/images/gallery/exhibitions/nepal-agritech-international-expo-3.webp",
    alt: "Nepal Agritech International Expo — Kathmandu, Nepal",
    category: "Nepal Agritech International Expo",
    year: "2022",
    location: "Kathmandu, Nepal",
    type: "exhibitions",
    moment: "Exhibitors showcasing to the trade floor",
  },
  {
    id: "nepal-buildcon-international-expo-1",
    src: "/images/gallery/exhibitions/nepal-buildcon-international-expo-1.webp",
    alt: "Nepal Buildcon International Expo — Kathmandu, Nepal",
    category: "Nepal Buildcon International Expo",
    year: "2022",
    location: "Kathmandu, Nepal",
    type: "exhibitions",
    moment: "Exhibitors showcasing to the trade floor",
  },
  {
    id: "nepal-buildcon-international-expo-2",
    src: "/images/gallery/exhibitions/nepal-buildcon-international-expo-2.webp",
    alt: "Nepal Buildcon International Expo — Kathmandu, Nepal",
    category: "Nepal Buildcon International Expo",
    year: "2022",
    location: "Kathmandu, Nepal",
    type: "exhibitions",
    moment: "Exhibitors showcasing to the trade floor",
  },
  {
    id: "nepal-buildcon-international-expo-3",
    src: "/images/gallery/exhibitions/nepal-buildcon-international-expo-3.webp",
    alt: "Nepal Buildcon International Expo — Kathmandu, Nepal",
    category: "Nepal Buildcon International Expo",
    year: "2022",
    location: "Kathmandu, Nepal",
    type: "exhibitions",
    moment: "Exhibitors showcasing to the trade floor",
  },
  {
    id: "futurex-industry-conference-1",
    src: "/images/gallery/conferences/futurex-industry-conference-1.webp",
    alt: "Futurex Industry Conference — New Delhi, India",
    category: "Futurex Industry Conference",
    year: "2022",
    location: "New Delhi, India",
    type: "conferences",
    moment: "Industry leaders in conversation",
  },
  {
    id: "futurex-industry-conference-2",
    src: "/images/gallery/conferences/futurex-industry-conference-2.webp",
    alt: "Futurex Industry Conference — New Delhi, India",
    category: "Futurex Industry Conference",
    year: "2022",
    location: "New Delhi, India",
    type: "conferences",
    moment: "Industry leaders in conversation",
  },
  {
    id: "futurex-industry-conference-3",
    src: "/images/gallery/conferences/futurex-industry-conference-3.webp",
    alt: "Futurex Industry Conference — New Delhi, India",
    category: "Futurex Industry Conference",
    year: "2022",
    location: "New Delhi, India",
    type: "conferences",
    moment: "Industry leaders in conversation",
  },
  {
    id: "futurex-industry-conference-4",
    src: "/images/gallery/conferences/futurex-industry-conference-4.webp",
    alt: "Futurex Industry Conference — New Delhi, India",
    category: "Futurex Industry Conference",
    year: "2022",
    location: "New Delhi, India",
    type: "conferences",
    moment: "Industry leaders in conversation",
  },
  {
    id: "futurex-industry-conference-5",
    src: "/images/gallery/conferences/futurex-industry-conference-5.webp",
    alt: "Futurex Industry Conference — New Delhi, India",
    category: "Futurex Industry Conference",
    year: "2022",
    location: "New Delhi, India",
    type: "conferences",
    moment: "Industry leaders in conversation",
  },
  {
    id: "futurex-industry-conference-6",
    src: "/images/gallery/conferences/futurex-industry-conference-6.webp",
    alt: "Futurex Industry Conference — New Delhi, India",
    category: "Futurex Industry Conference",
    year: "2022",
    location: "New Delhi, India",
    type: "conferences",
    moment: "Industry leaders in conversation",
  },
  {
    id: "ev-dynamics-conference-1",
    src: "/images/gallery/conferences/ev-dynamics-conference-1.webp",
    alt: "EV Dynamics Conference — New Delhi, India",
    category: "EV Dynamics Conference",
    year: "2022",
    location: "New Delhi, India",
    type: "conferences",
    moment: "Industry leaders in conversation",
  },
  {
    id: "ev-dynamics-conference-2",
    src: "/images/gallery/conferences/ev-dynamics-conference-2.webp",
    alt: "EV Dynamics Conference — New Delhi, India",
    category: "EV Dynamics Conference",
    year: "2022",
    location: "New Delhi, India",
    type: "conferences",
    moment: "Industry leaders in conversation",
  },
  {
    id: "ev-dynamics-conference-3",
    src: "/images/gallery/conferences/ev-dynamics-conference-3.webp",
    alt: "EV Dynamics Conference — New Delhi, India",
    category: "EV Dynamics Conference",
    year: "2022",
    location: "New Delhi, India",
    type: "conferences",
    moment: "Industry leaders in conversation",
  },
  {
    id: "bangladesh-3p-conference-1",
    src: "/images/gallery/conferences/bangladesh-3p-conference-1.webp",
    alt: "Bangladesh 3P Conference — Dhaka, Bangladesh",
    category: "Bangladesh 3P Conference",
    year: "2022",
    location: "Dhaka, Bangladesh",
    type: "conferences",
    moment: "Industry leaders in conversation",
  },
  {
    id: "bangladesh-3p-conference-2",
    src: "/images/gallery/conferences/bangladesh-3p-conference-2.webp",
    alt: "Bangladesh 3P Conference — Dhaka, Bangladesh",
    category: "Bangladesh 3P Conference",
    year: "2022",
    location: "Dhaka, Bangladesh",
    type: "conferences",
    moment: "Industry leaders in conversation",
  },
  {
    id: "bangladesh-3p-conference-3",
    src: "/images/gallery/conferences/bangladesh-3p-conference-3.webp",
    alt: "Bangladesh 3P Conference — Dhaka, Bangladesh",
    category: "Bangladesh 3P Conference",
    year: "2022",
    location: "Dhaka, Bangladesh",
    type: "conferences",
    moment: "Industry leaders in conversation",
  },
  {
    id: "futurex-webinar-1",
    src: "/images/gallery/webinars/futurex-webinar-1.webp",
    alt: "Futurex Industry Webinar — Online",
    category: "Futurex Industry Webinar",
    year: "2022",
    location: "Online",
    type: "webinars",
    moment: "Experts sharing insight, live online",
  },
  {
    id: "futurex-webinar-2",
    src: "/images/gallery/webinars/futurex-webinar-2.webp",
    alt: "Futurex Industry Webinar — Online",
    category: "Futurex Industry Webinar",
    year: "2022",
    location: "Online",
    type: "webinars",
    moment: "Experts sharing insight, live online",
  },
  {
    id: "futurex-webinar-3",
    src: "/images/gallery/webinars/futurex-webinar-3.webp",
    alt: "Futurex Industry Webinar — Online",
    category: "Futurex Industry Webinar",
    year: "2022",
    location: "Online",
    type: "webinars",
    moment: "Experts sharing insight, live online",
  },
  {
    id: "futurex-webinar-4",
    src: "/images/gallery/webinars/futurex-webinar-4.webp",
    alt: "Futurex Industry Webinar — Online",
    category: "Futurex Industry Webinar",
    year: "2022",
    location: "Online",
    type: "webinars",
    moment: "Experts sharing insight, live online",
  },
  {
    id: "futurex-webinar-5",
    src: "/images/gallery/webinars/futurex-webinar-5.webp",
    alt: "Futurex Industry Webinar — Online",
    category: "Futurex Industry Webinar",
    year: "2022",
    location: "Online",
    type: "webinars",
    moment: "Experts sharing insight, live online",
  },
  {
    id: "futurex-webinar-6",
    src: "/images/gallery/webinars/futurex-webinar-6.webp",
    alt: "Futurex Industry Webinar — Online",
    category: "Futurex Industry Webinar",
    year: "2022",
    location: "Online",
    type: "webinars",
    moment: "Experts sharing insight, live online",
  },
  {
    id: "futurex-webinar-7",
    src: "/images/gallery/webinars/futurex-webinar-7.webp",
    alt: "Futurex Industry Webinar — Online",
    category: "Futurex Industry Webinar",
    year: "2022",
    location: "Online",
    type: "webinars",
    moment: "Experts sharing insight, live online",
  },
  {
    id: "futurex-webinar-8",
    src: "/images/gallery/webinars/futurex-webinar-8.webp",
    alt: "Futurex Industry Webinar — Online",
    category: "Futurex Industry Webinar",
    year: "2022",
    location: "Online",
    type: "webinars",
    moment: "Experts sharing insight, live online",
  },
  {
    id: "futurex-virtual-platform-1",
    src: "/images/gallery/virtual-platform/futurex-virtual-platform-1.webp",
    alt: "Futurex Virtual Business Platform — Online",
    category: "Futurex Virtual Business Platform",
    year: "2022",
    location: "Online",
    type: "virtual-platform",
    moment: "Business meetings, hosted virtually",
  },
  {
    id: "futurex-virtual-platform-2",
    src: "/images/gallery/virtual-platform/futurex-virtual-platform-2.webp",
    alt: "Futurex Virtual Business Platform — Online",
    category: "Futurex Virtual Business Platform",
    year: "2022",
    location: "Online",
    type: "virtual-platform",
    moment: "Business meetings, hosted virtually",
  },
  {
    id: "futurex-virtual-platform-3",
    src: "/images/gallery/virtual-platform/futurex-virtual-platform-3.webp",
    alt: "Futurex Virtual Business Platform — Online",
    category: "Futurex Virtual Business Platform",
    year: "2022",
    location: "Online",
    type: "virtual-platform",
    moment: "Business meetings, hosted virtually",
  },
  {
    id: "futurex-virtual-platform-4",
    src: "/images/gallery/virtual-platform/futurex-virtual-platform-4.webp",
    alt: "Futurex Virtual Business Platform — Online",
    category: "Futurex Virtual Business Platform",
    year: "2022",
    location: "Online",
    type: "virtual-platform",
    moment: "Business meetings, hosted virtually",
  },
  {
    id: "futurex-virtual-platform-5",
    src: "/images/gallery/virtual-platform/futurex-virtual-platform-5.webp",
    alt: "Futurex Virtual Business Platform — Online",
    category: "Futurex Virtual Business Platform",
    year: "2022",
    location: "Online",
    type: "virtual-platform",
    moment: "Business meetings, hosted virtually",
  },
  {
    id: "futurex-virtual-platform-6",
    src: "/images/gallery/virtual-platform/futurex-virtual-platform-6.webp",
    alt: "Futurex Virtual Business Platform — Online",
    category: "Futurex Virtual Business Platform",
    year: "2022",
    location: "Online",
    type: "virtual-platform",
    moment: "Business meetings, hosted virtually",
  },
  {
    id: "futurex-virtual-platform-7",
    src: "/images/gallery/virtual-platform/futurex-virtual-platform-7.webp",
    alt: "Futurex Virtual Business Platform — Online",
    category: "Futurex Virtual Business Platform",
    year: "2022",
    location: "Online",
    type: "virtual-platform",
    moment: "Business meetings, hosted virtually",
  },
  {
    id: "futurex-virtual-platform-8",
    src: "/images/gallery/virtual-platform/futurex-virtual-platform-8.webp",
    alt: "Futurex Virtual Business Platform — Online",
    category: "Futurex Virtual Business Platform",
    year: "2022",
    location: "Online",
    type: "virtual-platform",
    moment: "Business meetings, hosted virtually",
  },
  {
    id: "futurex-media-coverage-1",
    src: "/images/gallery/media-coverage/futurex-media-coverage-1.webp",
    alt: "Futurex Media Coverage — Press",
    category: "Futurex Media Coverage",
    year: "2022",
    location: "Press",
    type: "media-coverage",
    moment: "Press coverage of a Futurex platform",
  },
  {
    id: "futurex-media-coverage-2",
    src: "/images/gallery/media-coverage/futurex-media-coverage-2.webp",
    alt: "Futurex Media Coverage — Press",
    category: "Futurex Media Coverage",
    year: "2022",
    location: "Press",
    type: "media-coverage",
    moment: "Press coverage of a Futurex platform",
  },
  {
    id: "futurex-media-coverage-3",
    src: "/images/gallery/media-coverage/futurex-media-coverage-3.webp",
    alt: "Futurex Media Coverage — Press",
    category: "Futurex Media Coverage",
    year: "2022",
    location: "Press",
    type: "media-coverage",
    moment: "Press coverage of a Futurex platform",
  },
  {
    id: "futurex-media-coverage-4",
    src: "/images/gallery/media-coverage/futurex-media-coverage-4.webp",
    alt: "Futurex Media Coverage — Press",
    category: "Futurex Media Coverage",
    year: "2022",
    location: "Press",
    type: "media-coverage",
    moment: "Press coverage of a Futurex platform",
  },
  {
    id: "futurex-media-coverage-6",
    src: "/images/gallery/media-coverage/futurex-media-coverage-6.webp",
    alt: "Futurex Media Coverage — Press",
    category: "Futurex Media Coverage",
    year: "2022",
    location: "Press",
    type: "media-coverage",
    moment: "Press coverage of a Futurex platform",
  },
  {
    id: "futurex-media-coverage-7",
    src: "/images/gallery/media-coverage/futurex-media-coverage-7.webp",
    alt: "Futurex Media Coverage — Press",
    category: "Futurex Media Coverage",
    year: "2022",
    location: "Press",
    type: "media-coverage",
    moment: "Press coverage of a Futurex platform",
  },
  {
    id: "futurex-media-coverage-8",
    src: "/images/gallery/media-coverage/futurex-media-coverage-8.webp",
    alt: "Futurex Media Coverage — Press",
    category: "Futurex Media Coverage",
    year: "2022",
    location: "Press",
    type: "media-coverage",
    moment: "Press coverage of a Futurex platform",
  },
];
